spring:
  application:
    name: pets-service
  datasource:
    url: jdbc:h2:mem:petsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    configUrl: /v3/api-docs/swagger-config

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
